#!/usr/bin/sh

# Possible arguments
#./build --install-local
#To build and install locally and get any error and what not.

#./build --install-system-wide
#To build and install system wide and get any error and what not. and be prompted for a sudo password when needed.

#./build --zip-file
#To build and the zip file and get any error and what not.

BUILD_DIR="builddir"
LOCAL_PREFIX="$HOME/.local"
GLOBAL_PREFIX="/usr"
UUID="mediaplayer@patapon.info"
TMP_DIR="/tmp/share/gnome-shell/extensions/$UUID"

build_type=$1
if [ -z $build_type ]; then
  build_type="--install-local"
fi

if [ -d "./$BUILD_DIR" ]; then
  echo "A current build directory already exists. Would you like to remove it?"
  select yn in "Yes" "No"; do
      case $yn in
          Yes )
            rm -rf "./$BUILD_DIR"
            echo "Build directory was removed succesufly"
          break;;
          No )
            echo "The old build directory must be removed first. Exiting"
          exit;;
      esac
  done
fi


case $build_type in
  "--install-local"*)
      meson $BUILD_DIR --prefix=$LOCAL_PREFIX
      ninja -C $BUILD_DIR install
    ;;
  "--install-system-wide"*)
      meson $BUILD_DIR --prefix=$GLOBAL_PREFIX
      sudo ninja -C $BUILD_DIR install
    ;;
  "--zip-file"*)
      meson $BUILD_DIR --prefix=/tmp
      ninja -C $BUILD_DIR install
      dest=$PWD
      cd $TMP_DIR
      zip -rq $dest/$UUID.zip .
      rm -rf $TMP_DIR
    ;;
esac
rm -rf $dest/$BUILD_DIR
echo "Done"
